# Generated by Django 5.0.4 on 2024-05-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Category_Name',
            new_name='Category',
        ),
    ]
