# Generated by Django 5.0.4 on 2024-05-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='Confirm_Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
